language: java

script:
    - ./gradlew clean
    - ./gradlew test
    - ./gradlew build
    - ./gradlew assemble
    - ./gradlew jar

cache:
  directories:
    - $HOME/.android

branches:
  only:
    - master
    - /^rel-.*$/

addons:
  artifacts:
    paths:
      - build/libs/*.jar